global using System;
global using Microsoft.Maui;
global using Microsoft.Maui.Hosting;
global using Microsoft.Maui.Graphics;
global using MauiControls = Microsoft.Maui.Controls;
global using Ory.Client.Api;
global using Ory.Client.Client;
global using Ory.Client.Model;
global using System.Threading.Tasks;
global using OryAuthNetMaui.Services;
global using Microsoft.Extensions.DependencyInjection;