global using System;
global using Microsoft.Maui;
global using Microsoft.Maui.Hosting;
global using Microsoft.Maui.Graphics;
global using MauiControls = Microsoft.Maui.Controls;
global using System.Threading.Tasks;
global using Microsoft.Extensions.DependencyInjection;
global using System.Collections.Generic;
global using OryAuthMauiShared.Services.Implementations;
global using OryAuthMauiShared.Services.Interfaces;